# Generated by Django 2.1.3 on 2020-05-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200525_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pdf',
            field=models.FileField(upload_to='Videos/'),
        ),
    ]
