# Generated by Django 2.1.3 on 2020-05-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200525_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='name',
        ),
    ]
