# Generated by Django 2.1.3 on 2020-05-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200525_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='inputLang',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='outputLang',
            field=models.CharField(default='Hindi', max_length=100),
        ),
    ]
