# Generated by Django 2.1.3 on 2020-05-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200528_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='inputLang',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='outputLang',
            field=models.CharField(max_length=100),
        ),
    ]
